// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-feedback-api/internal/prommetrics (interfaces: PromMetrics)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPromMetrics is a mock of PromMetrics interface.
type MockPromMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPromMetricsMockRecorder
}

// MockPromMetricsMockRecorder is the mock recorder for MockPromMetrics.
type MockPromMetricsMockRecorder struct {
	mock *MockPromMetrics
}

// NewMockPromMetrics creates a new mock instance.
func NewMockPromMetrics(ctrl *gomock.Controller) *MockPromMetrics {
	mock := &MockPromMetrics{ctrl: ctrl}
	mock.recorder = &MockPromMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromMetrics) EXPECT() *MockPromMetricsMockRecorder {
	return m.recorder
}

// IncCreate mocks base method.
func (m *MockPromMetrics) IncCreate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCreate")
}

// IncCreate indicates an expected call of IncCreate.
func (mr *MockPromMetricsMockRecorder) IncCreate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCreate", reflect.TypeOf((*MockPromMetrics)(nil).IncCreate))
}

// IncRemove mocks base method.
func (m *MockPromMetrics) IncRemove() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRemove")
}

// IncRemove indicates an expected call of IncRemove.
func (mr *MockPromMetricsMockRecorder) IncRemove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRemove", reflect.TypeOf((*MockPromMetrics)(nil).IncRemove))
}

// IncUpdate mocks base method.
func (m *MockPromMetrics) IncUpdate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncUpdate")
}

// IncUpdate indicates an expected call of IncUpdate.
func (mr *MockPromMetricsMockRecorder) IncUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncUpdate", reflect.TypeOf((*MockPromMetrics)(nil).IncUpdate))
}
