general:
  chunks : 2 

grpc:
  host : "localhost"
  port: 10000

postgres:
  conn_string: "postgres://postgres:postgres@localhost/postgres"
  max_open_conns: 15
  max_idle_conns: 5

kafka:
  brokers: 
          127.0.0.1:29092

prometheus:
  uri: "/metrics"
  host: "localhost"
  port: 2112

